### ISSUE TITLE
argocd installed as part of latest toolkit cannot be used

### ISSUE THREAD

**Issue by abalasu1** [ibm-garage-cloud/ibm-garage-iteration-zero#102]
argocd install using the operator in the latest toolkit cannot be used. argocd runs and the console can be accessed, but you cannot create apps, repositories, ...

Fix:
Edit the argocd instance in tools namespace and make the default policy admin.

oc edit argocd argocd -n tools

change
 rbac:
    defaultPolicy: role:readonly

to 

 rbac:
    defaultPolicy: role:admin

to fix the problem.

**Comment by seansund** [comment]
It can be used if you log in as admin or if you make the user part of the cluster admins group. I don't agree that the default policy role for every user should be admin

**Comment by seansund** [comment]
Here's what I propose:

1. Leave the default policy as `readonly` within the module when it installs
2. Address the issue of access by patching the default policy to `admin` in a post-installation step, particularly for clusters that will be used for education purposes
3. I will document the updated processes for configuring and managing ArgoCD introduced with the operator; from simple to more advanced scenarios - ibm-garage-cloud/planning#382
