### ISSUE TITLE
installing on existing ocp4 failed with cluster_type not found

### ISSUE THREAD

**Issue by vandepol** [ibm-garage-cloud/ibm-garage-iteration-zero#67]
Hey guys, tip/bug if you're installing to an existing ocp4 cluster. 

If you set cluster_type to ocp4,  I kept getting this error:

```
Error: Missing required argument

  on stage2-tekton.tf line 10, in module "dev_tools_tekton_resources":
  10: module "dev_tools_tekton_resources" {

The argument "cluster_type" is required, but no definition was found.
```

Looked at some of the other modules and changed 
stages-ocp4/stage2-tekton.tf file
`cluster_type             = module.dev_cluster.type`
to 
`cluster_type             = var.cluster_type`

Seems to be running now, can't figure out why original version isn't getting picked up, but I don't have much experience with terraform.

**Comment by seansund** [comment]
This has been resolved in subsequent releases
